# Generated by Django 5.2.4 on 2025-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(blank=True, choices=[('1', '1 Day'), ('2', '2 Days'), ('3', '3 Days'), ('4', '4 Days'), ('5', '5 Days'), ('6', '6 Days'), ('7', '7 Days'), ('14', '2 Weeks')], max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_type',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends'), ('corporate', 'Corporate')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_travelers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Safari'), ('luxury', 'Luxury Safari'), ('combo', 'Beach + Safari Combo'), ('honeymoon', 'Honeymoon Safari')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
