# Generated by Django 5.2.4 on 2025-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_booking_duration_booking_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Safari'), ('luxury', 'Luxury Safari'), ('combo', 'Family Safari'), ('honeymoon', 'Honeymoon ')], max_length=20),
        ),
    ]
